[package]
name = "zed-harper"
description = "Harper language server support for the Zed editor"
version = "0.0.1"
edition = "2024"
publish = false
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.1.0"
